# ============================================================================
# Script: 02_nmf_per_sample
# Module: 02_meta_programs
# Description:
#   Run NMF decomposition on a per-sample basis for LUAD tumor epithelial cells.
#   Designed for server/HPC execution due to high computational cost.
#   Each sample is normalized, top 5000 genes are selected, and NMF is run
#   across ranks 4-9 with 10 runs per rank.
#
# Input:
#   Result_2/results_data/01_LUAD_epi_anno_final_NMF_input.rds
#   (generated by 01_nmf_input_preparation.R)
#
# Output:
#   Result_2/results_data/NMF_results/<sample>_rank4_9_nruns10.RDS
#   (consumed by 03_mp_signature_identification.R)
#
# Usage:
#   Rscript scripts/02_meta_programs/02_nmf_per_sample.R
# ============================================================================

library(Seurat)
library(NMF)
library(parallel)
library(tidyverse)
library(readxl)
library(dplyr)
library(stringr)
library(tibble)

# ---- Configuration ----

#' Load the NMF input Seurat object.
#'
#' @param input_path Path to the RDS file containing the LUAD epithelial object.
#' @return Seurat object.
load_nmf_input <- function(input_path) {
  if (!file.exists(input_path)) {
    stop("[ERROR] NMF input file not found: ", input_path)
  }
  message("[INFO] Loading NMF input from: ", input_path)
  readRDS(file = input_path)
}

#' Normalize and scale data, then select top genes per sample.
#'
#' @param seurat_obj Seurat object containing all epithelial cells.
#' @param n_top_genes Number of top genes to retain per sample. Default 5000.
#' @param n_cores Number of cores for parallel normalization. Default 1.
#' @return Named list of non-negative expression matrices (genes x cells).
prepare_sample_matrices <- function(seurat_obj, n_top_genes = 5000, n_cores = 1) {
  message("[INFO] Splitting object by sample...")
  epi_list <- SplitObject(seurat_obj, split.by = "Sample")

  message("[INFO] Processing ", length(epi_list), " sample(s) for normalization and gene selection")

  expr_list <- mclapply(names(epi_list), function(sam) {
    message("[INFO] ", Sys.time(), " | Normalizing sample: ", sam)

    seu <- epi_list[[sam]]
    seu <- NormalizeData(seu)

    exp_nor <- GetAssayData(seu, layer = "data")
    mean_expr <- sort(rowMeans(exp_nor), decreasing = TRUE)
    kept_genes <- names(mean_expr)[seq_len(min(n_top_genes, length(mean_expr)))]

    seu <- ScaleData(seu, features = kept_genes)
    expr <- GetAssayData(seu, layer = "scale.data")
    expr[expr < 0] <- 0  # Enforce non-negativity for NMF

    expr
  }, mc.cores = n_cores)

  names(expr_list) <- names(epi_list)
  expr_list
}

#' Run NMF on a single sample expression matrix.
#'
#' @param sam Sample name.
#' @param expr Non-negative expression matrix (genes x cells).
#' @param output_dir Directory to save NMF RDS results.
#' @param rank_range Integer vector of ranks to test. Default 4:9.
#' @param nrun Number of NMF runs per rank. Default 10.
#' @param nmf_method NMF algorithm. Default "snmf/r".
#' @return NMF result object.
run_nmf_single_sample <- function(sam,
                                   expr,
                                   output_dir,
                                   rank_range  = 4:9,
                                   nrun        = 10,
                                   nmf_method  = "snmf/r") {
  message("            ", Sys.time(), " | Running NMF for: ", sam)

  nmf_res <- nmf(
    x      = expr,
    rank   = rank_range,
    nrun   = nrun,
    method = nmf_method
  )

  # Save result
  out_file <- file.path(
    output_dir,
    paste0(sam, "_rank", min(rank_range), "_", max(rank_range),
           "_nruns", nrun, ".RDS")
  )

  saveRDS(nmf_res, file = out_file)
  message("            [SAVE] ", out_file)

  nmf_res
}

# ---- Main Function ----

#' Run per-sample NMF decomposition on LUAD tumor epithelial cells.
#'
#' @param input_path Path to the input Seurat object (.rds).
#' @param output_dir Directory for NMF result files.
#' @param n_top_genes Number of top genes per sample. Default 5000.
#' @param rank_range Integer vector of ranks to test. Default 4:9.
#' @param nrun Number of runs per rank. Default 10.
#' @param nmf_method NMF algorithm. Default "snmf/r".
#' @param n_cores Number of parallel cores for NMF. Default 16.
#' @return Named list of NMF results per sample.
run_nmf_analysis <- function(
    input_path  = file.path(RESULT_2_DIR, "results_data", "01_LUAD_epi_anno_final_NMF_input.rds"),
    output_dir  = file.path(RESULT_2_DIR, "results_data", "NMF_results"),
    n_top_genes = 5000,
    rank_range  = 4:9,
    nrun        = 10,
    nmf_method  = "snmf/r",
    n_cores     = 16
) {
  # Ensure output directory exists
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  }

  # Load data
  LUAD_epi <- load_nmf_input(input_path)

  # Prepare expression matrices
  expr_list <- prepare_sample_matrices(LUAD_epi, n_top_genes = n_top_genes, n_cores = n_cores)

  message("\n[INFO] Starting NMF decomposition on ", length(expr_list), " sample(s)")
  message("[INFO] Rank range: ", paste(rank_range, collapse = ":"))
  message("[INFO] Runs per rank: ", nrun)
  message("[INFO] Method: ", nmf_method)
  message("[INFO] Parallel cores: ", n_cores)

  # Run NMF per sample in parallel
  mnf_list <- mclapply(names(expr_list), function(sam) {
    tryCatch(
      {
        run_nmf_single_sample(
          sam         = sam,
          expr        = expr_list[[sam]],
          output_dir  = output_dir,
          rank_range  = rank_range,
          nrun        = nrun,
          nmf_method  = nmf_method
        )
      },
      error = function(e) {
        warning("[ERROR] NMF failed for sample ", sam, ": ", conditionMessage(e))
        NULL
      }
    )
  }, mc.cores = n_cores)

  names(mnf_list) <- names(expr_list)

  message("\n[INFO] NMF decomposition complete.")
  message("[INFO] Results saved to: ", output_dir)

  invisible(mnf_list)
}

# ---- Entry Point ----

if (!interactive()) {
  # Attempt to source config.R; if not available, use defaults
  config_path <- file.path(
    dirname(dirname(dirname(dirname(getwd())))), "config.R"
  )
  if (!file.exists(config_path)) {
    config_path <- "~/LUAD-scMetaPrograms/config.R"
  }
  if (file.exists(config_path)) {
    source(config_path)
  } else {
    warning("[WARN] config.R not found. Using default paths.")
  }

  # Run with defaults or config-derived paths
  run_nmf_analysis()
}
