# ============================================================================
# Script: bin.R
# Module: 02_meta_programs/utils
# Description:
#   Utility functions for expression binning and bin-matched control signature
#   generation.
# ============================================================================

#' Prepare a matrix or vector for binning
#'
#' If a matrix is provided, apply FUN to summarize rows/columns.
#' If numeric, sort the values.
#'
#' @param mat A matrix or NULL.
#' @param FUN Function to apply. Default rowMeans.
#' @return Numeric vector.
.prepare_mat <- function(mat, FUN = rowMeans) {
    if (!is.null(dim(mat))) x <- FUN(mat)
    if (is.numeric(x)) x <- sort(x)
    return(x)
}


#' Match groups to bins
#'
#' @param Group Character vector of group identifiers.
#' @param bins Named vector of bin assignments.
#' @return List of matched bin members.
.match_bins <- function(Group, bins) {
    .check_arg(arg = Group)
    .check_missing(Group = Group, ref = bins)
    binID <- bins[Group]
    binmatches <- sapply(binID, function(id) names(bins)[bins == id], simplify = FALSE)
    binmatches
}


#' Sample from bins
#'
#' @param bins Named vector of bins.
#' @param n Number of samples per bin. Default 100.
#' @param replace Logical; sample with replacement. Default FALSE.
#' @return Character vector of sampled values.
.sample_bins <- function(bins, n = 100, replace = FALSE) {
    .check_sample_size(bins = bins, n = n, replace = replace)
    sapply(bins, function(bin) {
        sample(bin, size = n, replace = replace)
    }, simplify = FALSE) %>%
        unlist(use.names = FALSE)
}


#' Control Signatures From Expression Bins
#'
#' Return a control signature for the signature or Group provided.
#' Control signatures are generated by binning average row values and sampling
#' from the resulting bins such that every value in the original signature has
#' n bin-matched values in the output.
#'
#' @param Group A character vector of gene names.
#' @param mat A matrix. Default NULL.
#' @param x A named numeric vector to generate bins from. If NULL, computed
#'   from mat. Default NULL.
#' @param bins A named character vector with gene names as names and bin IDs
#'   as values. Default NULL.
#' @param nbin Numeric. Number of bins. Default 30.
#' @param n Numeric. Number of control values per group value. Default 100.
#' @param replace Logical. Allow sampling with replacement. Default FALSE.
#' @param ... Additional arguments passed to bin().
#' @return Character vector of length n * length(Group).
#' @rdname binmatch
#' @export
binmatch <- function(Group,
                     mat = NULL,
                     x = NULL,
                     bins = NULL,
                     nbin = 30,
                     n = 100,
                     replace = FALSE,
                     ...) {
    .check_args_exist(x = x, data = mat, bins = bins)
    if (!is.null(x) | !is.null(mat)) {
        bins <- bin(x = x, mat = mat, breaks = nbin, ...)
    }
    binmatches <- .match_bins(Group = Group, bins = bins)
    binsamples <- .sample_bins(bins = binmatches, n = n, replace = replace)
    binsamples
}


#' Generate Equally-Sized Bins
#'
#' Generate equally-sized bins from a named numeric vector or from a summary
#' statistic of a matrix's rows.
#'
#' @param mat A matrix over whose rows to calculate a summary statistic.
#'   Default NULL.
#' @param x A named numeric vector to generate bins from. Default NULL.
#' @param breaks The number of desired bins. Default 30.
#' @param FUN Function to apply to each row of a matrix. Must return a single
#'   numeric value per row. Default rowMeans.
#' @return Named numeric vector with bin IDs as values.
#' @rdname bin
#' @export
bin <- function(mat = NULL,
                x = NULL,
                breaks = 30,
                FUN = rowMeans) {
    if (!is.null(mat)) x <- .prepare_mat(mat, FUN = FUN)
    .check_arg(arg = x)
    binIDs <- cut(seq_along(x), breaks = breaks, labels = FALSE, include.lowest = TRUE)
    .name_binIDs(binIDs = binIDs, x = x)
}
